package com.example.quince.room.database

val crearTabla = """
    CREATE TABLE IF NOT EXISTS recomendacion (
                                    id INTEGER PRIMARY KEY,
                                    consejos Varchar(255)
                                );"""


val recomendaciones = """
    INSERT OR REPLACE INTO recomendacion (id, consejos) VALUES
                                (1, "El cielo parece un poco cubierto, quizá sea día de hacer cosas en casa."),
                                (2, "Hoy lleva una chaqueta ligera por si refresca."),
                                (3, "¿Qué tal si te llevas un paraguas por si acaso?, eso o ver una peli en casa."),
                                (4, "Hoy podrías planificar una cena tranquila en casa ya que el cielo está un poco feo."),
                                (5, "Podrías crear un ambiente acogedor en casa y no salir. ¡Relax day!."),
                                (6, "Es un buen momento para leer un libro."),
                                (7, "Considera hacer ejercicio en casa...o no, ante día cubierto mejor disfrutar bajo techo."),
                                (8, "¿Qué tal si te llevas un paraguas por si acaso? pero antes sería buena idea preparar una taza de café o té caliente."),
                                (9, "Organiza tu espacio de trabajo en casa."),
                                (10, "Ante un día con cielos cubiertos, casi mejor no ir a muchos sitios."),
                                (11, "El día despejado es perfecto para paseos al aire libre."),
                                (12, "Aprovecha el sol para tomar vitamina D."),
                                (13, "Haz una barbacoa en el jardín o parque si te apetece, lleva ropa cómoda."),
                                (14, "Realiza ejercicio al aire libre, como running."),
                                (15, "Organiza una fiesta al aire libre con amigos, que siempre está genial."),
                                (16, "Toma fotografías en paisajes despejados."),
                                (17, "Instala una sombrilla si vas a estar mucho tiempo al sol."),
                                (18, "Asegúrate de llevar protector solar."),
                                (19, "Planifica un picnic en el parque."),
                                (20, "Disfruta de las vistas despejadas desde un mirador."),
                                (21, "A pesar de las nubes, puedes disfrutar de un paseo ligero, ¿no crees?."),
                                (22, "Lleva un paraguas por si hay alguna lluvia sorpresa."),
                                (23, "Es un buen día para una excursión corta."),
                                (24, "Disfruta de la brisa suave en un día nublado."),
                                (25, "Aprovecha para hacer senderismo en áreas sombreadas."),
                                (26, "Considera visitar un museo o galería de arte."),
                                (27, "Planifica una reunión al aire libre con sombra."),
                                (28, "Disfruta de una comida ligera en un parque sombreado."),
                                (29, "Observa las nubes y disfruta de la tranquilidad."),
                                (30, "Es un buen día para fotografía con luz difusa."),
                                (31, "Lleva un paraguas o un impermeable si sales."),
                                (32, "Disfruta de una película mientras llueve afuera."),
                                (33, "Prepara una sopa o algo caliente para comer."),
                                (34, "Escucha el sonido de la lluvia para relajarte."),
                                (35, "Asegúrate de tener botas impermeables si sales."),
                                (36, "Es un buen momento para organizar tu armario."),
                                (37, "Aprovecha para escribir o hacer algo creativo en casa."),
                                (38, "Verifica que tus techos y ventanas estén bien cerradas."),
                                (39, "Es un buen día para preparar té o infusiones."),
                                (40, "Disfruta de un baño caliente, ¡hoy te lo mereces!."),
                                (41, "Aprovecha el sol para hacer actividades al aire libre."),
                                (42, "Protégete del sol con gorra y protector solar."),
                                (43, "Haz ejercicio al aire libre para disfrutar del sol."),
                                (44, "Planifica un día de playa o piscina."),
                                (45, "Disfruta de un día soleado en el jardín."),
                                (46, "Haz fotos con la luz solar para obtener mejores imágenes."),
                                (47, "Asegúrate de hidratarte mucho en días soleados."),
                                (48, "Organiza una reunión al aire libre aprovechando el buen tiempo."),
                                (49, "Disfruta de la brisa suave en un parque soleado."),
                                (50, "Es un buen día para una excursión o picnic."),
                                (51, "Bebe mucha agua para mantenerte hidratado."),
                                (52, "Evita la exposición directa al sol durante las horas punta."),
                                (53, "Utiliza ropa ligera y transpirable."),
                                (54, "Aprovecha los espacios fríos, como centros comerciales."),
                                (55, "Planifica actividades matinales o por la tarde para evitar el calor."),
                                (56, "Utiliza protectores solares de alta SPF."),
                                (57, "Asegúrate de tener acceso a sombra si estás al aire libre."),
                                (58, "Evita las actividades intensas bajo el sol directo."),
                                (59, "Prepara bebidas refrescantes como smoothies o jugos."),
                                (60, "Asegúrate de mantener tu hogar bien ventilado o con aire acondicionado."),
                                (61, "Organiza tu espacio de trabajo o hogar aprovechando la calma de un día nuboso."),
                                (62, "Elige una película o serie que te guste y dedica el día a disfrutar de tu tiempo."),
                                (63, "Haz una sesión de yoga o pilates en casa para mantener la flexibilidad y el ánimo."),
                                (64, "Prepara una deliciosa receta de pastelería para llevar un poco de calor a tu hogar."),
                                (65, "Toma fotografías de tus plantas o objetos decorativos aprovechando la luz suave del día."),
                                (66, "Lee un libro o toma un curso en línea para aprender algo nuevo en un día tranquilo."),
                                (67, "Juega a un juego de mesa o haz un puzzle con tus amigos o familiares."),
                                (68, "Escribe en tu diario o agenda tus tareas pendientes para mantener el orden en tus días."),
                                (69, "Dedica tiempo a meditar o practicar respiración profunda en un día nuboso."),
                                (70, "Crea un ambiente acogedor en casa con velas o luces tenues para relajarte."),
                                (71, "Mantén una actitud positiva ante cualquier cambio de tiempo."),
                                (72, "Aprende a predecir el clima observando las nubes y fenómenos naturales."),
                                (73, "Planifica tus actividades teniendo en cuenta el pronóstico del tiempo."),
                                (74, "Asegúrate de llevar siempre un paraguas o impermeable en tu bolso."),
                                (75, "Prepara una lista de actividades tanto dentro como fuera de casa para cualquier tiempo."),
                                (76, "Aprende a aprovechar el tiempo para actividades creativas."),
                                (77, "Mantén tu teléfono cargado para consultar el clima en cualquier momento."),
                                (78, "Hoy va a ser un buen día."),
                                (79, "Aprende a respetar la naturaleza y sus cambios climáticos."),
                                (80, "Ayuda a los demás, en general, ante cualquier cambio en el clima.");
"""

//He modificado la variable de recomendaciones agregando más. Antes la tenía tal que así:
//val recomendaciones = """
//    INSERT OR REPLACE INTO recomendacion (id, consejos) VALUES
//                                (1, "Si el cielo está muy nuboso, es buen momento para realizar actividades bajo techo."),
//                                (2, "En un día muy nuboso, lleva una chaqueta ligera para mantenerte cómodo."),
//                                (3, "Cuando el día está muy nuboso, es recomendable llevar un paraguas por si acaso."),
//                                (4, "Si el cielo está cubierto, es buena idea llevar una bufanda o sombrero para mayor comodidad."),
//                                (5, "En un día cubierto, puedes disfrutar de actividades al aire libre sin preocuparte por el sol."),
//                                (6, "Cuando está cubierto, el clima es ideal para hacer ejercicio sin los efectos directos del sol."),
//                                (7, "Si el día está despejado, recuerda usar protector solar para proteger tu piel de la radiación UV."),
//                                (8, "En un día despejado, las gafas de sol son esenciales para proteger tus ojos del sol."),
//                                (9, "Si el cielo está despejado, es un buen momento para hacer actividades al aire libre."),
//                                (10, "Con algunas nubes en el cielo, disfruta de actividades fuera de casa sin el calor intenso del sol."),
//                                (11, "En un día con nubes, puedes caminar sin la preocupación de quemaduras solares."),
//                                (12, "Si hay algunas nubes, es el momento perfecto para un paseo tranquilo sin el calor abrumador."),
//                                (13, "Si está lloviendo, lleva un paraguas para evitar mojarte."),
//                                (14, "Si llueve mucho, usa un impermeable para mantenerte seco."),
//                                (15, "En un día lluvioso, evita caminar por lugares con encharcamientos."),
//                                (16, "Cuando hace sol, recuerda beber agua con frecuencia para mantenerte hidratado."),
//                                (17, "En un día soleado, asegúrate de aplicar protector solar varias veces durante el día."),
//                                (18, "Si está muy soleado, usa sombrero o gafas de sol para proteger tu rostro y ojos."),
//                                (19, "Si hace mucho calor, hidrátate constantemente para evitar golpes de calor."),
//                                (20, "Recuerda llevar una botella de agua cuando hace calor para mantenerte fresco."),
//                                (21, "En un día caluroso, busca sombra siempre que puedas para evitar el golpe de calor."),
//                                (22, "Mantén una actitud positiva ante cualquier cambio en el clima y disfruta de lo que te rodea."),
//                                (23, "Recuerda hacer pausas cuando realices actividades al aire libre, sobre todo si hace calor o frío."),
//                                (24, "No olvides llevar tu teléfono móvil cargado, siempre es bueno estar preparado."),
//                                (25, "Lleva siempre una chaqueta ligera o suéter, ya que el clima puede cambiar rápidamente."),
//                                (26, "Ten a mano un pequeño botiquín con lo esencial, nunca sabes cuándo lo podrías necesitar."),
//                                (27, "No olvides revisar el pronóstico del clima antes de salir, te ayudará a estar preparado."),
//                                (28, "Si vas a realizar actividades al aire libre, asegúrate de llevar protector solar y agua."),
//                                (29, "Recuerda siempre estar consciente de tu entorno y de las condiciones del clima para tu seguridad."),
//                                (30, "Recuerda siempre ir atento a las noticias sobre el clima para estar preparado.");
//"""