package com.example.quince.room.database

val crearTabla = """
    CREATE TABLE IF NOT EXISTS recomendacion (
                                    id INTEGER PRIMARY KEY,
                                    consejos Varchar(255)
                                );"""

val recomendaciones = """
    INSERT OR REPLACE INTO recomendacion (id, consejos) VALUES
    (1, "Ante un cielo cubierto, no te deprimas. Prepara una chaqueta ligera de abrigo y un café calentito."),
    (2, "Con el día cubierto, no dejes que el gris te apague. Te aconsejo una chaqueta de entretiempo, un jersey fino y una sonrisa que ya verás que sienta bien."),
    (3, "Nubes amenazantes en el horizonte, lleva un paraguas por si acaso llueve. Podrías preparte una tarde de película si quieres y puedes evitar salir."),
    (4, "Un cielo cubierto no tiene por qué ser aburrido. Te sugiero un plan de cena que te haga olvidar lo gris del día."),
    (5, "Día gris, alma alegre. Te recomiendo un jersey, calcetines divertidos y un día de relax que demuestre que la felicidad no depende del clima."),
    (6, "Cielo encapotado. Te aconsejo un look casual: sudadera cómoda, pantalón y un libro que te transporte lejos de cualquier nube."),
    (7, "¿Nubes por todas partes? Te recomiendo ropa deportiva, música y convertir tu casa en tu propio gimnasio."),
    (8, "Prepárate para un día de esos. Te sugiero chaqueta impermeable, paraguas de color y una taza de té."),
    (9, "Día gris. Te recomiendo un look cómodo y tomar algo de chocolate caliente para que tu día al menos sea de color."),
    (10, "Cielos cubiertos. Te aconsejo ropa de abrigo ligero y planes divertidos (jugar a algun videojuego quizá)."),
    (11, "¡Día despejado! Te recomiendo camiseta y un paseo por el campo (o por la playa)."),
    (12, "Sol radiante. Te sugiero ropa ligera, transpirable y una sonrisa que nunca viene mal."),
    (13, "Cielo limpio. Te aconsejo pantalones cortos y si puedes hacer una barbacoa estaría genial. Esto o salir a dar un paseo por ahí."),
    (14, "Día despejado. Te recomiendo camiseta y una carrera que demuestre que el running es más que ejercicio, es pasarlo bien"),
    (15, "Cielo claro, alegría total. Te sugiero ropa que grite diversión y una actitud alegre. ¿Habrá abierto algún sitio cerca para visitarlo?."),
    (16, "Día soleado. Te aconsejo ropa cómoda, gorra y una cámara lista para capturar momentos."),
    (17, "Sal preparado como si el sol fuera tu amigo. Ropa ligera y gafas de sol. Ah, y algo contra el calor."),
    (18, "Picnic a la vista. Te recomiendo un look tipo ropa cómoda"),
    (19, "Día de mirador. Prepárate a salir con una chaqueta y mucha alegría, quizá puedas quedar con amigos o familiares hoy."),
    (20, "Día perfecto para ser tú. Te sugiero un look casual: vaqueros, camiseta y zapatillas para andar."),
    (21, "Nubes ligeras. Te recomiendo una chaqueta y un paseo."),
    (22, "Nubes en el cielo. Paraguas, chaqueta ligera y la actitud de quien sabe que un poco de lluvia no te detiene."),
    (23, "Día nuboso. Te aconsejo ropa de senderismo, botas y salir a que te de el aire."),
    (24, "Brisa suave. Una chaqueta ligera y a salir a disfrutar de esta brisa."),
    (25, "Para senderismo en zonas sombreadas: ropa técnica, zapatillas de trekking y una chaqueta."),
    (26, "Día nuboso perfecto para un look casual: vaqueros, jersey y visita a un museo."),
    (27, "Prepara ropa cómoda y fresca para una reunión al aire libre con sombra."),
    (28, "Nubes y temperatura suave: ropa ligera y perfecta para una comida en un parque."),
    (29, "Día para ropa cómoda y tranquila: observar nubes puede ser relajante."),
    (30, "Para fotografía: ropa neutra, cómoda y una cámara para capturar momentos bonitos."),
    (31, "Día de lluvia: pijama, manta, palomitas y una buena película en casa."),
    (32, "Con lluvia, prepara ropa calentita, botas impermeables y una sopa casera."),
    (33, "Día lluvioso perfecto para ropa de estar en casa: calcetines, sudadera y té caliente."),
    (34, "Si sales con lluvia: impermeable, botas de agua y paraguas son imprescindibles."),
    (35, "Lluvia en puerta: ropa impermeable, calcetines secos y verificar que todo esté cerrado."),
    (36, "Día lluvioso ideal para ropa cómoda, infusiones calientes y un buen libro."),
    (37, "Con lluvia, un buen baño caliente y ropa de descanso son el plan perfecto."),
    (38, "Día de lluvia: ropa cómoda, ambiente creativo y aprovecha para escribir o crear."),
    (39, "Lluvia en casa: momento perfecto para reorganizar tu armario con ropa de temporada."),
    (40, "Ante la lluvia, mantén siempre a mano un paraguas y una chaqueta impermeable."),
    (41, "Sol radiante: ropa ligera, protector solar y ganas de actividades al aire libre."),
    (42, "Día soleado: pantalones cortos, camiseta, gorra, gafas de sol y protector solar."),
    (43, "Para hacer ejercicio al sol: ropa transpirable, gorra y mucha hidratación."),
    (44, "Día de playa o piscina: bañador, toalla, chanclas y protección solar."),
    (45, "Jardín con sol: ropa fresca, sombrero y ganas de disfrutar al aire libre."),
    (46, "Día soleado para fotos: ropa clara, gafas de sol y cámara preparada."),
    (47, "Con sol: ropa ligera, botella de agua y gorra para mantenerte hidratado."),
    (48, "Reunión al aire libre: ropa fresca, informal y protección solar."),
    (49, "Parque soleado: vestimenta ligera y ganas de disfrutar la brisa."),
    (50, "Día de excursión o picnic: ropa cómoda, zapatillas y gorra."),
    (51, "Calor intenso: ropa ligera, transpirable y muy suelta."),
    (52, "Días calurosos: shorts, camiseta, gafas de sol y mucha agua."),
    (53, "Con altas temperaturas: ropa clara, ligera y que no pegue al cuerpo."),
    (54, "Calor: ropa fresca, sandalias y busca espacios con aire acondicionado."),
    (55, "Temperaturas altas: ropa ligera para actividades matinales o tardías."),
    (56, "Día caluroso: ropa clara, protector solar y gorra."),
    (57, "Con calor: ropa que te proteja del sol, manga larga ligera y sombrero."),
    (58, "Temperaturas altas: ropa suelta, clara y que te permita movimiento."),
    (59, "Calor intenso: ropa fresca, sandalias y preparar bebidas refrescantes."),
    (60, "Con altas temperaturas: ropa ligera y mantener la casa fresca."),
    (61, "Día nuboso: ropa cómoda de oficina y ganas de organizar tu espacio."),
    (62, "Cielo nuboso: outfit casual, manta y una serie para disfrutar."),
    (63, "Día tranquilo: ropa de yoga, calcetines y ambiente relajado."),
    (64, "Nuboso perfecto para ropa cómoda y preparar algo dulce en la cocina."),
    (65, "Día suave: ropa neutra y ganas de tomar fotos de interiores."),
    (66, "Cielo nuboso: ropa cómoda, taza de té y un buen libro."),
    (67, "Día tranquilo: ropa cómoda para juegos de mesa con familia."),
    (68, "Nuboso: look casual, taza de café y momento para escribir."),
    (69, "Día gris: ropa de descanso y momento para meditar."),
    (70, "Cielo nuboso: ropa cómoda, luces tenues y ambiente acogedor."),
    (71, "Mantén ropa preparada para cualquier cambio de tiempo."),
    (72, "Aprende a vestirte según las señales del clima."),
    (73, "Planifica tu vestuario según el pronóstico del día."),
    (74, "Lleva siempre un paraguas plegable y una chaqueta ligera."),
    (75, "Prepara un kit de ropa para diferentes condiciones climáticas."),
    (76, "Ropa versátil para aprovechar cualquier momento del día."),
    (77, "Mantén una aplicación de clima para vestirte adecuadamente."),
    (78, "Hoy va a ser un buen día, vístete con confianza."),
    (79, "Respeta el clima con la ropa adecuada."),
    (80, "Ayuda a otros eligiendo la ropa más apropiada.");
"""